# Generated by Django 4.0.3 on 2022-04-12 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('text', models.TextField(max_length=8192)),
            ],
        ),
        migrations.CreateModel(
            name='Reputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=32)),
                ('questions', models.ManyToManyField(to='baseApplication.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='reputation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApplication.reputation'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=8192)),
                ('isCorrect', models.BooleanField()),
                ('reputation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApplication.reputation')),
            ],
        ),
    ]
