# Generated by Django 4.0.3 on 2022-04-13 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApplication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='authors',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='authors',
            new_name='author',
        ),
    ]
