# Generated by Django 4.0.3 on 2022-04-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reputation',
            name='value',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
    ]
