# Generated by Django 4.0.3 on 2022-04-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApplication', '0002_profile_answer_author_question_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='baseApplication.question'),
        ),
    ]
