# Generated by Django 4.0.3 on 2022-04-13 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApplication', '0002_rename_authors_dislike_author_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dislike',
            old_name='author',
            new_name='authors',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='author',
            new_name='authors',
        ),
    ]
