# Generated by Django 4.0.3 on 2022-04-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApplication', '0003_rename_author_dislike_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='reputation',
            field=models.IntegerField(default=123),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='reputation',
            field=models.IntegerField(default=1343),
            preserve_default=False,
        ),
    ]
