# Generated by Django 4.0.3 on 2022-04-13 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApplication', '0003_alter_answer_managers_alter_question_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='tag',
            new_name='title',
        ),
    ]
