# Generated by Django 4.0.3 on 2022-04-13 08:42

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApplication', '0004_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='answer',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='baseApplication.question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='publish_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='question',
            name='publish_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='tag',
            name='last_update',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='questions',
            field=models.ManyToManyField(blank=True, to='baseApplication.question'),
        ),
    ]
