# Generated by Django 4.0.3 on 2022-04-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('baseApplication', '0005_answer_answer_answer_publish_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='answer',
            new_name='question',
        ),
    ]
