# Generated by Django 4.0.3 on 2022-04-13 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseApplication', '0006_rename_answer_answer_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='reputation',
            name='author',
            field=models.ForeignKey(default=124, on_delete=django.db.models.deletion.CASCADE, to='baseApplication.profile'),
            preserve_default=False,
        ),
    ]
